#################################
# Render Rmarkdown documents
#################################

.PHONY: book
book: results/data_processed.RData results/archs4/archs4_data_processed.RData results/models.RData results/archs4/archs4_models.RData $(RMD_FILES)
	Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', new_session=TRUE)"

results/archs4/archs4_res.csv:
	mkdir -p results/archs4
	Rscript "preprocess_archs4.R"

results/data_processed.RData:
	mkdir -p results
	Rscript process_data.R data/bioqc_geo_oracle_dump/BIOQC_RES_DATA_TABLE.csv data/bioqc_geo_oracle_dump/materialized_views/BIOQC_SELECTED_SAMPLES_TSET_DATA_MATERIALIZED\ VIEW.csv results/data_processed.RData

results/models.RData: config.R results/data_processed.RData
	mkdir -p results
	Rscript correct_for_correlation.R results/models.RData results/data_processed.RData

results/archs4/archs4_data_processed.RData: results/archs4/archs4_res.csv
	mkdir -p results
	Rscript process_data.R ./results/archs4/archs4_res.csv ./results/archs4/archs4_meta.csv results/archs4/archs4_data_processed.RData

results/archs4/archs4_models.RData: config.R results/archs4/archs4_data_processed.RData
	mkdir -p results
	Rscript correct_for_correlation.R results/archs4/archs4_models.RData results/archs4/archs4_data_processed.RData



# empty target can be used to force regeneration of files
.FORCE:
