```{r, include=FALSE, message=FALSE}
library(MASS)
library(BioQC)
library(stringr)
library(gridExtra)
library(dplyr)
library(readr)
library(cowplot)
library(readxl)
library(tidyr)
source("../scripts/config.R")
```

```{r load_data, message=FALSE, include=FALSE, cache=TRUE}
load('../results/data_processed.RData')
load('../results/models.RData')
```

```{r raw-corr-plots, fig.width=200, fig.height=24}
tmp_cutoff = 0.05 / 2000
ci = function(x, intercept, slope, sigma, sign=1) {
 x * slope + intercept + sign * qnorm(1-tmp_cutoff, mean=0, sd=sigma) 
}
data_corr %>% 
  filter(str_detect(SIGNATURE, "^BIOQC") | str_detect(SIGNATURE, "^GTEX")) %>% 
  ggplot(aes(x=ref_score, y=score)) + 
  geom_point(alpha=.25, size=1) + 
  facet_grid(TGROUP~SIGNATURE) + 
  geom_abline(aes(slope=slope, intercept=intercept), colour="red") + 
  geom_ribbon(aes(color="interval", ymax=ci(ref_score, intercept, slope, sigma, 1), ymin=ci(ref_score, intercept, slope, sigma, -1), alpha=.2, show.legend = TRUE)) +
  theme_bw()

```


```{r heterogeneitygtex, cache=TRUE, echo=FALSE, fig.cap="Tissue heterogeneity assessed with the reference signatures. The annotated tissues are listed in rows, the significantly enriched signatures in columns. If a signature has been found to be significantly enriched in a sample, the sample will count towards the number indicated in the matrix. All contaminations per sample are included, *i.e.* a sample can appear multiple times in a row. "}
contam_count = data_corr %>%
  filter(pcorr_adj < P_THRES) %>%
  group_by(TGROUP, SIGNATURE) %>%
  summarise(cnt = n_distinct(GSM))

# # by species
# contam_count = data_corr %>%
#   inner_join(sample_species) %>%
#   filter(pcorr_adj < P_THRES) %>%
#   group_by(TGROUP, SIGNATURE, ORGANISM) %>%
#   summarise(cnt = n_distinct(GSM)) %>%
#   filter(SIGNATURE %in% reference_signatures$REF_SIG)

contam_count %>%
  filter(SIGNATURE %in% reference_signatures$REF_SIG) %>%
  ggplot(aes(x=factor(SIGNATURE, levels=reference_signatures$REF_SIG), y=TGROUP)) +
      geom_tile(aes(fill = cnt)) +
      geom_text(aes(label=cnt)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      scale_x_discrete(drop=FALSE) +
      ylab("reference tissue") +
      xlab("detected signature")
```

```{r heterogeneityall, fig.width=8, fig.height=20, cache=TRUE, echo=FALSE, fig.cap="Tissue heterogeneity assessed with the BioQC signatures. The annotated tissues are listed in rows, the significantly enriched signatures in columns. If a signature has been found to be significantly enriched in a sample, the sample will count towards the number indicated in the matrix. All contaminations per sample are included, *i.e.* a sample can appear multiple times in a row."}
bioqc_signatures = selected_signatures %>% filter(str_detect(SIGNATURE, 'BIOQC')) %>% pull("SIGNATURE")
chunks = cut_interval(1:length(bioqc_signatures), length=25, labels=FALSE)

plots = lapply(unique(chunks), function(i) {
  tmp_signatures = bioqc_signatures[chunks==i]
  contam_count %>%
  filter(SIGNATURE %in% tmp_signatures) %>%
  ggplot(aes(x=factor(SIGNATURE, levels=tmp_signatures), y=TGROUP)) +
      geom_tile(aes(fill = cnt)) +
      geom_text(aes(label=cnt)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      scale_x_discrete(drop=FALSE) +
      ylab("reference tissue") +
      xlab("detected signature") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1, size=10)) +
      background_grid(major = "xy", minor="xy")
})

plot_grid(plotlist = plots, ncol=1, nrow = length(plots))
```

```{r heterogeneitybar, echo=FALSE, cache=TRUE, fig.cap="Fraction of heterogenous samples per tissue. Heterogeneity has been assessed using both the reference signatures and the signatures from BioQC. A sample only counts once to the fraction, even if multiple signatures are found to be enriched. "}
heterogenous_samples = data_corr %>%
                          filter(pcorr_adj < P_THRES) %>%
                          pull(GSM) %>%
                          unique()

bioqc_meta %>%
  mutate(heterogenous = ifelse(GSM %in% heterogenous_samples, TRUE, FALSE)) %>%
  group_by(TGROUP) %>%
  summarise(total = n(), heterogenous = sum(heterogenous)) %>%
  mutate(fraction = heterogenous/total) %>%
  ggplot(aes(x=TGROUP, y=fraction)) + geom_bar(stat='identity')



```

