```{r, include=FALSE, message=FALSE}
library(MASS)
library(BioQC)
library(stringr)
library(gridExtra)
library(dplyr)
library(readr)
library(cowplot)
source("../scripts/config.R")
```
# Redo analysis for ARCHS4

```{r load_data45, message=FALSE, include=FALSE, cache=TRUE}
load('../results/archs4/archs4_data_processed.RData')
load('../results/archs4/archs4_models.RData')
```

## Quick plots to check if everything is ok
```{r}
ref_data = data2 %>% inner_join(select(reference_signatures, "REF_SIG"), by=c("SIGNATURE"="REF_SIG"))
ggplot(ref_data, aes(x=SIGNATURE, y=score)) + geom_boxplot() + facet_wrap(~TGROUP) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
ref_data %>% filter(TGROUP == "blood", SIGNATURE == 'GTEX_Blood') %>% ggplot(aes(x=score)) + geom_histogram()
ref_data %>% ggplot(aes(x=ref_score, y=score)) + geom_point() + facet_grid(REF_SIG ~ SIGNATURE, scales="free")
```

## Sample count by tissue
```{r}
data2 %>% select(GSM, TGROUP) %>% group_by(TGROUP) %>% summarise(count = n_distinct(GSM))
```


## same analysis...
```{r heterogeneitygtex2, cache=TRUE, echo=FALSE, fig.cap="Tissue heterogeneity assessed with the reference signatures. The annotated tissues are listed in rows, the significantly enriched signatures in columns. If a signature has been found to be significantly enriched in a sample, the sample will count towards the number indicated in the matrix. All contaminations per sample are included, *i.e.* a sample can appear multiple times in a row. "}
contam_count = data_corr %>%
  filter(pcorr_adj < P_THRES) %>%
  group_by(TGROUP, SIGNATURE) %>%
  summarise(cnt = n_distinct(GSM))

## disabled correlation correction...
# contam_count = data_corr %>%
#   filter(qvalue < P_THRES) %>%
#   group_by(TGROUP, SIGNATURE) %>%
#   summarise(cnt = n_distinct(GSM))

contam_count %>%
  filter(SIGNATURE %in% reference_signatures$REF_SIG) %>%
  ggplot(aes(x=factor(SIGNATURE, levels=reference_signatures$REF_SIG), y=TGROUP)) +
      geom_tile(aes(fill = cnt)) +
      geom_text(aes(label=cnt)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      scale_x_discrete(drop=FALSE) +
      ylab("reference tissue") +
      xlab("detected signature")
```

```{r heterogeneityall2, fig.width=8, fig.height=35, cache=TRUE, echo=FALSE, fig.cap="Tissue heterogeneity assessed with the BioQC signatures. The annotated tissues are listed in rows, the significantly enriched signatures in columns. If a signature has been found to be significantly enriched in a sample, the sample will count towards the number indicated in the matrix. All contaminations per sample are included, *i.e.* a sample can appear multiple times in a row."}
bioqc_signatures = selected_signatures %>% filter(str_detect(SIGNATURE, 'BIOQC')) %>% pull("SIGNATURE")
chunks = cut_interval(1:length(bioqc_signatures), length=15, labels=FALSE)

plots = lapply(unique(chunks), function(i) {
  tmp_signatures = bioqc_signatures[chunks==i]
  contam_count %>%
  filter(SIGNATURE %in% tmp_signatures) %>%
  ggplot(aes(x=factor(SIGNATURE, levels=tmp_signatures), y=factor(TGROUP, levels=reference_signatures$TGROUP))) +
      geom_tile(aes(fill = cnt)) +
      geom_text(aes(label=cnt)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      scale_x_discrete(drop=FALSE) +
      ylab("reference tissue") +
      xlab("detected signature") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1, size=10)) +
      background_grid(major = "xy", minor="xy") +
    scale_y_discrete(drop=FALSE)
})

plot_grid(plotlist = plots, ncol=1, nrow = length(plots))
```

```{r heterogeneitybar, echo=FALSE, cache=TRUE, fig.cap="Fraction of heterogenous samples per tissue. Heterogeneity has been assessed using both the reference signatures and the signatures from BioQC. A sample only counts once to the fraction, even if multiple signatures are found to be enriched. "}
heterogenous_samples = data_corr %>%
                          filter(pcorr_adj < P_THRES) %>%
                          pull(GSM) %>%
                          unique()

bioqc_meta %>%
  mutate(heterogenous = ifelse(GSM %in% heterogenous_samples, TRUE, FALSE)) %>%
  group_by(TGROUP) %>%
  summarise(total = n(), heterogenous = sum(heterogenous)) %>%
  mutate(fraction = heterogenous/total) %>%
  ggplot(aes(x=TGROUP, y=fraction)) + geom_bar(stat='identity')



```
